// @ts-nocheck — auto-generated by Stellar CLI, do not edit manually
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64, 
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CBDKF3AXX3WA4N4GKCLGACG6L7JFTG7JJWQNXEASD63SCRLF2J7KRIUA",
  }
} as const

export const Errors = {
  1: {message:"InvalidAmount"},
  2: {message:"InvalidUnlockTime"},
  3: {message:"SavingsNotFound"},
  4: {message:"StillLocked"},
  5: {message:"AlreadyWithdrawn"},
  6: {message:"MaxSavingsReached"}
}

export type DataKey = {tag: "Count", values: readonly [string]} | {tag: "Savings", values: readonly [string, u32]};


export interface SavingsGoal {
  amount: i128;
  token: string;
  unlock_at: u64;
  withdrawn: boolean;
}

export interface Client {
  /**
   * Construct and simulate a lock transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Lock tokens until `unlock_at` (unix timestamp in seconds).
   * Returns the savings goal ID for this user.
   */
  lock: ({saver, token, amount, unlock_at}: {saver: string, token: string, amount: i128, unlock_at: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<u32>>>

  /**
   * Construct and simulate a get_goal transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Read a savings goal by ID.
   */
  get_goal: ({saver, goal_id}: {saver: string, goal_id: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<SavingsGoal>>>

  /**
   * Construct and simulate a withdraw transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Withdraw tokens from a matured savings goal back to the saver.
   */
  withdraw: ({saver, goal_id}: {saver: string, goal_id: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<i128>>>

  /**
   * Construct and simulate a get_count transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Return how many savings goals a user has created.
   */
  get_count: ({saver}: {saver: string}, options?: MethodOptions) => Promise<AssembledTransaction<u32>>

  /**
   * Construct and simulate a is_unlocked transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Check whether a goal has matured and is ready to withdraw.
   */
  is_unlocked: ({saver, goal_id}: {saver: string, goal_id: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<boolean>>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAABgAAAAAAAAANSW52YWxpZEFtb3VudAAAAAAAAAEAAAAAAAAAEUludmFsaWRVbmxvY2tUaW1lAAAAAAAAAgAAAAAAAAAPU2F2aW5nc05vdEZvdW5kAAAAAAMAAAAAAAAAC1N0aWxsTG9ja2VkAAAAAAQAAAAAAAAAEEFscmVhZHlXaXRoZHJhd24AAAAFAAAAAAAAABFNYXhTYXZpbmdzUmVhY2hlZAAAAAAAAAY=",
        "AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAAAgAAAAEAAAAAAAAABUNvdW50AAAAAAAAAQAAABMAAAABAAAAAAAAAAdTYXZpbmdzAAAAAAIAAAATAAAABA==",
        "AAAAAQAAAAAAAAAAAAAAC1NhdmluZ3NHb2FsAAAAAAQAAAAAAAAABmFtb3VudAAAAAAACwAAAAAAAAAFdG9rZW4AAAAAAAATAAAAAAAAAAl1bmxvY2tfYXQAAAAAAAAGAAAAAAAAAAl3aXRoZHJhd24AAAAAAAAB",
        "AAAAAAAAAGVMb2NrIHRva2VucyB1bnRpbCBgdW5sb2NrX2F0YCAodW5peCB0aW1lc3RhbXAgaW4gc2Vjb25kcykuClJldHVybnMgdGhlIHNhdmluZ3MgZ29hbCBJRCBmb3IgdGhpcyB1c2VyLgAAAAAAAARsb2NrAAAABAAAAAAAAAAFc2F2ZXIAAAAAAAATAAAAAAAAAAV0b2tlbgAAAAAAABMAAAAAAAAABmFtb3VudAAAAAAACwAAAAAAAAAJdW5sb2NrX2F0AAAAAAAABgAAAAEAAAPpAAAABAAAAAM=",
        "AAAAAAAAABpSZWFkIGEgc2F2aW5ncyBnb2FsIGJ5IElELgAAAAAACGdldF9nb2FsAAAAAgAAAAAAAAAFc2F2ZXIAAAAAAAATAAAAAAAAAAdnb2FsX2lkAAAAAAQAAAABAAAD6QAAB9AAAAALU2F2aW5nc0dvYWwAAAAAAw==",
        "AAAAAAAAAD5XaXRoZHJhdyB0b2tlbnMgZnJvbSBhIG1hdHVyZWQgc2F2aW5ncyBnb2FsIGJhY2sgdG8gdGhlIHNhdmVyLgAAAAAACHdpdGhkcmF3AAAAAgAAAAAAAAAFc2F2ZXIAAAAAAAATAAAAAAAAAAdnb2FsX2lkAAAAAAQAAAABAAAD6QAAAAsAAAAD",
        "AAAAAAAAADFSZXR1cm4gaG93IG1hbnkgc2F2aW5ncyBnb2FscyBhIHVzZXIgaGFzIGNyZWF0ZWQuAAAAAAAACWdldF9jb3VudAAAAAAAAAEAAAAAAAAABXNhdmVyAAAAAAAAEwAAAAEAAAAE",
        "AAAAAAAAADpDaGVjayB3aGV0aGVyIGEgZ29hbCBoYXMgbWF0dXJlZCBhbmQgaXMgcmVhZHkgdG8gd2l0aGRyYXcuAAAAAAALaXNfdW5sb2NrZWQAAAAAAgAAAAAAAAAFc2F2ZXIAAAAAAAATAAAAAAAAAAdnb2FsX2lkAAAAAAQAAAABAAAD6QAAAAEAAAAD" ]),
      options
    )
  }
  public readonly fromJSON = {
    lock: this.txFromJSON<Result<u32>>,
        get_goal: this.txFromJSON<Result<SavingsGoal>>,
        withdraw: this.txFromJSON<Result<i128>>,
        get_count: this.txFromJSON<u32>,
        is_unlocked: this.txFromJSON<Result<boolean>>
  }
}